plugins {
    id 'multiloader-loader'

    alias(libs.plugins.loom)
}

//apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/repository-publishers/codinglitch.gradle'
//apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/curseforge.gradle'
//apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/modrinth.gradle'

dependencies {
    minecraft(libs.fabric.minecraft)

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    }

    modImplementation libs.bundles.fabric.modImpl

    modCompileOnly(libs.fabric.computercraft.api)

    modCompileOnly(libs.fabric.voicechat)
    modCompileOnly(libs.fabric.voicechatinteraction)

    modCompileOnly(libs.fabric.valkyrienskies) { transitive = false }

    modLocalRuntime libs.bundles.fabric.environment
}

fabricApi {
    configureDataGeneration() {
        setOutputDirectory(project(":fabric").file("src/main/generated"))
    }
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
            source sourceSets.development
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
            source sourceSets.development
        }
        gameTest {
            server()
            setConfigName("Fabric Game Test")
            vmArg "-Dfabric-api.gametest=1"
            vmArg "-Dfabric.log.level=debug"
            runDir("runs/gametest")
            ideConfigGenerated(true)
            source sourceSets.development
        }
    }
}