plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "com.modrinth.minotaur" version "2.+"
    id 'com.matthewprenger.cursegradle' version '1.4.0'
}

apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/repository-publishers/codinglitch.gradle'
apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/curseforge.gradle'
apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/modrinth.gradle'

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}"){
        exclude module: "fabric-resource-loader-v0" // 🤷‍♂️
    }

    // --- Dependencies --- \\

    compileOnly "com.codinglitch.lexiconfig:lexiconfig-api:${lexiconfig_version}"
    modRuntimeOnly "com.codinglitch.lexiconfig:lexiconfig-fabric:${lexiconfig_version}"

    compileOnly "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"
    modCompileOnly "maven.modrinth:simple-voice-chat:fabric-${minecraft_version}-${voicechat_version}"
    modLocalRuntime "maven.modrinth:simple-voice-chat:fabric-${minecraft_version}-${voicechat_version}"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${mixin_extras_version}")))

    // --- Compatibilities --- \\

    // Audio Player
    modLocalRuntime "maven.modrinth:audioplayer:fabric-${minecraft_version}-${audioplayer_version}"
    modLocalRuntime "maven.modrinth:admiral:0.4.5+1.21+fabric"

    // ComputerCraft
    modCompileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-fabric-api:${cc_version}")
    //modRuntimeOnly("cc.tweaked:cc-tweaked-${minecraft_version}-fabric:${cc_version}")

    // Voice Chat Interaction
    modCompileOnly "maven.modrinth:voice-chat-interaction:fabric-${minecraft_version}-${voicechat_interaction_version}"
    modCompileOnly "eu.pb4:polymer-reg-sync-manipulator:${polymer_version}"
    modLocalRuntime "maven.modrinth:voice-chat-interaction:fabric-${minecraft_version}-${voicechat_interaction_version}"
    modLocalRuntime "eu.pb4:polymer-reg-sync-manipulator:${polymer_version}"

    // Vibrative Voice
    implementation "com.codinglitch.vibrativevoice:vibrativevoice-api:${vibrative_voice_version}"
    //modCompileOnly "maven.modrinth:vibrative-voice:${vibrative_voice_version}"
    //modRuntimeOnly "maven.modrinth:vibrative-voice:${vibrative_voice_version}"

    // Valkyrien Skies
    if (valkyrien_skies_env_versions.contains(minecraft_version)) {
        modCompileOnly("org.valkyrienskies:valkyrienskies-${minecraft_version.replace('.','')}-fabric:${valkyrien_skies_version}")
        modLocalRuntime("org.valkyrienskies:valkyrienskies-${minecraft_version.replace('.','')}-fabric:${valkyrien_skies_version}") {
            exclude group: "com.simibubi.create" // create 5 💔💔
        }
    }

    // Create
    if (create_env_versions.contains(minecraft_version)) {
        //modLocalRuntime("com.simibubi.create:create-fabric-$minecraft_version:$create_fabric_version")
    }

    // JEI / REI
    if (recipe_viewer == "jei") {
        // compile against the JEI API but do not include it at runtime
        modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
        modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}")
        // at runtime, use the full JEI jar for Fabric
        modLocalRuntime("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
    } else if (recipe_viewer == "rei") {
        // TODO: add rei to devenv
    }

    // Config mods
    if (config_mod == "configured") {
        modLocalRuntime "com.mrcrayfish:configured-fabric:${configured_version}"
    } else if (config_mod == "cloth_config") {

    } else if (config_mod == "owo") {

    } else if (config_mod == "config_screens") {

    }
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            runDir("runs/client")
            source sourceSets.development
        }
        server {
            server()
            setConfigName("Fabric Server")
            runDir("runs/server")
            source sourceSets.development
        }
    }
}

fabricApi {
    configureDataGeneration() {
        setOutputDirectory(project(":fabric").file("src/main/generated"))
    }
}