plugins {
    id 'multiloader-loader'
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id "com.modrinth.minotaur" version "2.+"
    id 'com.matthewprenger.cursegradle' version '1.4.0'
}

apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/repository-publishers/codinglitch.gradle'
apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/curseforge.gradle'
apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/modrinth.gradle'

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // --- Dependencies --- \\

    compileOnly "com.codinglitch.lexiconfig:lexiconfig-api:${lexiconfig_version}"
    modRuntimeOnly "com.codinglitch.lexiconfig:lexiconfig-fabric:${lexiconfig_version}"

    compileOnly "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"
    modRuntimeOnly "maven.modrinth:simple-voice-chat:fabric-${minecraft_version}-${voicechat_version}"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${mixin_extras_version}")))

    localRuntime "com.electronwill.night-config:core:${night_config_version}"
    localRuntime "com.electronwill.night-config:toml:${night_config_version}"

    // --- Compatibilities --- \\

    // Voice Chat Interaction
    modCompileOnly "maven.modrinth:voice-chat-interaction:fabric-${minecraft_version}-${voicechat_interaction_version}"
    modCompileOnly "eu.pb4:polymer-reg-sync-manipulator:${polymer_version}+${minecraft_version}"
    modLocalRuntime "maven.modrinth:voice-chat-interaction:fabric-${minecraft_version}-${voicechat_interaction_version}"
    modLocalRuntime "eu.pb4:polymer-reg-sync-manipulator:${polymer_version}+${minecraft_version}"

    // Vibrative Voice
    implementation "com.codinglitch.vibrativevoice:vibrativevoice-api:${vibrative_voice_version}"
    //modCompileOnly "maven.modrinth:vibrative-voice:${vibrative_voice_version}"
    //modRuntimeOnly "maven.modrinth:vibrative-voice:${vibrative_voice_version}"

    // Valkyrien Skies
    if (valkyrien_skies_enabled.toBoolean()) {
        modCompileOnly("org.valkyrienskies:valkyrienskies-${minecraft_version.replace('.','')}-fabric:${valkyrien_skies_version}")
        modLocalRuntime("org.valkyrienskies:valkyrienskies-${minecraft_version.replace('.','')}-fabric:${valkyrien_skies_version}")
    }

    // JEI / REI
    if (recipe_viewer == "jei") {
        modLocalRuntime("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
    } else if (recipe_viewer == "rei") {
        // TODO: add rei to devenv
    }

    // Config mods
    if (config_mod == "configured") {
        //modLocalRuntime "com.mrcrayfish:configured-fabric:${configured_version}"
    } else if (config_mod == "cloth_config") {

    } else if (config_mod == "owo") {

    } else if (config_mod == "config_screens") {

    }
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
            source sourceSets.development
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
            source sourceSets.development
        }
    }
}

fabricApi {
    configureDataGeneration() {
        setOutputDirectory(project(":fabric").file("src/main/generated"))
    }
}