plugins {
    id 'multiloader-common'
}

sourceSets {
    development {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.output
        runtimeClasspath += main.output
    }

    datagen {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }

    apiJava {
        canBeResolved = true
    }

    developmentImplementation.extendsFrom implementation
    developmentRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }

        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')

    // --- Common --- \\

    apiJava project(path: ':api', configuration: 'apiJava')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)

    dependsOn(configurations.apiJava)
    source(configurations.apiJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)

    dependsOn(configurations.apiJava)
    source(configurations.apiJava)
}

tasks.named("sourcesJar", Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.apiJava)
    from(configurations.apiJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

// honestly no idea what im doing at this point
tasks.register("substituteResources", Copy) {
    from sourceSets.datagen.output.resourcesDir // we only need to replace the resources with the datagen one
    into sourceSets.main.output.resourcesDir

    duplicatesStrategy DuplicatesStrategy.EXCLUDE
}

tasks.register('publishModrinth') {
    dependsOn(":${project.name}:modrinth")
}

tasks.register('publishCurseForge') {
    dependsOn(":${project.name}:curseforge")
}

tasks.register('publishSites') {
    dependsOn publishModrinth, publishCurseForge
}