# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.4.6.6
group=com.codinglitch.simpleradio
java_version=17

# Common
minecraft_version=1.20.4
mod_name=SimpleRadio
mod_author=CodinGlitch
mod_id=simpleradio
license=GNU GPLv3
credits=
description=Adds a simple radio item for the Simple Voice Chat mod!
minecraft_version_range=[1.20.2,1.20.4]

# Fabric
fabric_version=0.97.2+1.20.4
fabric_loader_version=0.16.13
fabric_minecraft_version_range=>=1.20.2 <=1.20.4

# Forge
forge_version=49.2.0
forge_version_range=[48,)

# NeoForge
neoforge_version=20.4.131-beta
neoforge_version_range=[1,)

# Environment
recipe_viewer=jei
config_mod=configured

create_env_versions = [1.20.1]
valkyrien_skies_env_versions = [1.20.1]

# Dependencies
voicechat_api_version=2.5.0
voicechat_version=2.5.0

night_config_version=3.6.6

lexiconfig_version=1.4.17-a

mixin_extras_version=0.4.1

# Compatibilities
voicechat_interaction_version=1.0.5
polymer_version=0.7.1

vibrative_voice_version=1.0.0

valkyrien_skies_api_version=1.1.0+e26d9059c0
valkyrien_skies_version=2.3.0-beta.5+2e2d63a807

create_version = 6.0.3-71
ponder_version = 1.0.51
flywheel_version = 1.0.1
registrate_version = MC1.20-1.3.3

jei_version=17.3.1.5

configured_version=1.20.4-2.2.3

# Publishing
name_template=[_uppercase_loader] Simple Radio _minecraft_ver-_version
modrinth_id=S7b8mMXS
curseforge_id=820070
supported_versions=1.20.2,1.20.3,1.20.4

requiredDependencies=lexiconfig
optionalDependencies=voice-chat-interaction,valkyrienskies,create

release_type=release
debug_mode=false

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
