# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.4.6.6
group=com.codinglitch.simpleradio
java_version=17

# Common
minecraft_version=1.19.2
mod_name=SimpleRadio
mod_author=CodinGlitch
mod_id=simpleradio
license=GNU GPLv3
credits=
description=Adds a simple radio item for the Simple Voice Chat mod!
minecraft_version_range=[1.19,1.19.2]

# Fabric
fabric_version=0.77.0+1.19.2
fabric_loader_version=0.16.13
fabric_minecraft_version_range=>=1.19 <=1.19.2

# Forge
forge_version=43.5.0
forge_version_range=[43,)

# NeoForge
neoforge_version=47.1.97
neoforge_version_range=[1,)

# Environment
recipe_viewer=jei
config_mod=configured

create_enabled = true
valkyrien_skies_enabled = false

# Dependencies
voicechat_api_version=2.4.11
voicechat_version=2.4.32

night_config_version=3.6.6

lexiconfig_version=1.4.17-b

mixin_extras_version=0.4.1

joml_version=1.10.0

# Compatibilities
voicechat_interaction_version=1.0.5
polymer_version=0.0.3

vibrative_voice_version=1.0.0

valkyrien_skies_api_version=1.1.0+e26d9059c0
valkyrien_skies_version=2.3.0-beta.5+2e2d63a807

create_version = 0.5.1.i-59
registrate_version = MC1.19-1.1.5
flywheel_version = 0.6.11-22

jei_version=11.5.0.297

configured_version=1.20.1-2.2.3

# Publishing
name_template=[_uppercase_loader] Simple Radio _minecraft_ver-_version
modrinth_id=S7b8mMXS
curseforge_id=820070
supported_versions=1.19,1.19.1,1.19.2

requiredDependencies=lexiconfig
optionalDependencies=voice-chat-interaction,valkyrienskies,create

release_type=release
debug_mode=false

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
