# Project
version=4.4.6.8
group=com.codinglitch.simpleradio
java_version=17

# Common
mod_name=Simple Radio
mod_author=CodinGlitch
mod_id=simpleradio
license=GNU GPLv3
credits=
description=Adds a simple radio item for the Simple Voice Chat mod!

# Publishing
name_template=[_uppercase_loader] Simple Radio _minecraft_ver-_version
modrinth_id=S7b8mMXS
curseforge_id=820070
supported_versions=1.20,1.20.1

requiredDependencies=lexiconfig
optionalDependencies=voice-chat-interaction,valkyrien-skies,create

release_type=beta
debug_mode=false

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
