plugins {
    id 'multiloader-common'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
}

minecraft {
    version(minecraft_version)
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if(aw.exists()){
        accessWideners(aw)
    }
}

dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'

    // --- Dependencies --- \\

    implementation "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"
    compileOnly "com.codinglitch.lexiconfig:lexiconfig-api:${lexiconfig_version}"
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))

    // --- Compatibilities --- \\

    // Vibrative Voice
    implementation "com.codinglitch.vibrativevoice:vibrativevoice-api:${vibrative_voice_version}"

    // Valkyrien Skies
    if (valkyrien_skies_env_versions.contains(minecraft_version))
        compileOnly("org.valkyrienskies.core:api:${valkyrien_skies_api_version}")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
